[build]
  command = "npm install"
  publish = "static"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  # Set ANTHROPIC_API_KEY in Netlify UI

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Permissions-Policy = "camera=(), microphone=()"

[dev]
  command = "python app.py"
  targetPort = 5001
  publish = "static"
