[build]
  command = "npm install && pip install -r requirements.txt"
  publish = "static"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.9.0"
  NODE_VERSION = "18"
  # Set ANTHROPIC_API_KEY in Netlify UI

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["duckduckgo-search"]
  included_files = ["app.py", "requirements.txt"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Permissions-Policy = "camera=(), microphone=()"

[dev]
  command = "python app.py"
  targetPort = 5001
  publish = "static"
