[build]
  command = "pip install -r requirements.txt && python -c 'from app import app; open("render/_redirects", "w").write("/* /index.html 200"); open("render/_headers", "w").write("/*\n  X-Frame-Options: DENY\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: same-origin\n  Permissions-Policy: camera=(), microphone=()\n")'"
  publish = "render"
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["duckduckgo-search"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Permissions-Policy = "camera=(), microphone=()"
